### ISSUE TITLE
Documentation Generation Fails with File Already Exists

### ISSUE THREAD

**Issue by gfs** [FuLagann/csharp-docs-generator#15]
## Repro
https://github.com/microsoft/OAT/pull/13/files

## Exception Details
```
Exception calling "ExtractToDirectory" with "2" argument(s): "The file 
'd:\a\OAT\OAT\__temp\libs\serilog\2.9.0\_rels\.rels' already exists."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('d:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
 
Error: The process 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
##[error]The process 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
    at ExecState._setResult (d:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:561:25)
    at ExecState.CheckComplete (d:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:544:18)
    at ChildProcess.<anonymous> (d:\a\_actions\FuLagann\csharp-docs-generator\v1.0\node_modules\@actions\exec\lib\toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by FuLagann** [comment]
This error happened because it downloaded the same dependency library twice. I tried to make sure it wouldn't download duplicate libraries. But trying to fix it it looks like the best I could do for now is soft crash the method where it happens.

It should work now, thank you for posting this issue.
