### ISSUE TITLE
Index.html is empty

### ISSUE THREAD

**Issue by Morasiu** [FuLagann/csharp-docs-generator#29]
As you can see [here](https://github.com/Morasiu/Clockify.Net/blob/gh-pages/index.html) it is empty.

Should it be empty?

**Comment by FuLagann** [comment]
All your API html files are empty. Looking at your `.csproj` file, you didn't make it generate the documentation file that's needed. I updated the Getting Started section to include this since it does seem to be a bit obscure.

Just add the following to your `.csproj` into the `PropertyGroup` and it should be generating correctly:

```xml
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```

**Comment by Morasiu** [comment]
Added this and it didn't help.

**Comment by PeerConradi** [comment]
I'm having the same issue: https://github.com/PeerConradi/munityData

**Comment by lzinga** [comment]
I am experiencing the same problem mentioned in this issue. I do not have the xml mentioned from @FuLagann missing from the csproj. Here are some of the issues I am seeing in the logs.

```
Gathering template data.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\c0b2994e-e028-4e28-b9f8-311808113959', '__temp-81da16c5-e595-4ad6-b34f-b07c31efe3be/')"
Could not find file [__temp-81da16c5-e595-4ad6-b34f-b07c31efe3be//template.json]
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at D:\a\_actions\FuLagann\csharp-docs-generator\master\lib\input.js:61:33
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\FuLagann\csharp-docs-generator\master\lib\input.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Running: dotnet build
```
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\21653d74-4f8f-4328-9d46-0a158b56cce3', '__temp-81da16c5-e595-4ad6-b34f-b07c31efe3be//libs/selenium.webdriver/4.0.0-alpha07')"
Exception calling "ExtractToDirectory" with "2" argument(s): "The file 
'D:\a\AutoWeb\AutoWeb\__temp-81da16c5-e595-4ad6-b34f-b07c31efe3be\libs\selenium.webdriver\4.0.0-alpha07\_rels\.rels' 
already exists."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
 
Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\FuLagann\csharp-docs-generator\master\node_modules\@actions\exec\lib\toolrunner.js:574:25)
    at ExecState.CheckComplete (D:\a\_actions\FuLagann\csharp-docs-generator\master\node_modules\@actions\exec\lib\toolrunner.js:557:18)
    at ChildProcess.<anonymous> (D:\a\_actions\FuLagann\csharp-docs-generator\master\node_modules\@actions\exec\lib\toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

This generates the html pages, however they are all empty.

**Comment by sabuto** [comment]
shame this was closed seeing as it is not fixed
